services:
  db:
    container_name: cloud_db_dev
    image: postgres:alpine
    env_file:
      - .env.dev.db.local
    ports:
      - 5432:5432
    volumes:
      - db_data_dev:/var/lib/postgresql/data
volumes:
  db_data_dev: