services:
  web:
    container_name: cloud_web_prod
    image: ghcr.io/starlightroad/cloud-prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    env_file:
      - .env.prod.local
      - .env.prod.db.local
      - .env.prisma.local
    ports:
      - 3002:3002
    expose:
      - 3002
    depends_on:
      - db
  db:
    container_name: cloud_db_prod
    image: postgres:alpine
    env_file:
      - .env.prod.db.local
    ports:
      - 5432:5432
    volumes:
      - db_data_prod:/var/lib/postgresql/data
volumes:
  db_data_prod: