import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/_ui/globals.css";
import Sidebar from "@/app/_ui/components/sidebar";

const geistSans = localFont({
  src: "./_ui/fonts/GeistVF.woff",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.className} antialiased flex h-full`}>
        <div className="w-full max-w-screen-lg mx-auto lg:border-x lg:border-x-accent flex">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
